version: '3.7'

services:
  db:
    image: mysql
    container_name: fligno_db
    volumes:
      - "./db/.data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: fligno
      MYSQL_USER: fligno_user
      MYSQL_PASSWORD: test123
      MYSQL_ROOT_PASSWORD: test123
    expose:
      - 33060
      - 3306
    networks:
      - internal
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fligno_phpmyadmin
    environment: 
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
    - db
    ports:
    - 8888:80
    networks:
      - internal

  client:
    build: client
    container_name: fligno_client
    depends_on:
      - server
    ports:
      - 8080:3000
    command: npm run webpack-dev
    networks:
      - public

  server:
    build: server
    container_name: fligno_server
    ports:
      - 9090:80
    depends_on:
      - db
    volumes:
      - "./server:/var/www/html"
    networks:
      - internal

networks:
  public:
    external: false
  internal:
    external: false