version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: fligno_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=fligno
      - MYSQL_USER=fligno_user
      - MYSQL_PASSWORD=test123
    volumes:
      - ./db/.data:/var/lib/mysql:rw,delegated
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - internal

  client:
    build: client
    container_name: fligno_client
    depends_on:
      - server
    ports:
      - 8080:5000
    volumes:
      - "./client:/server"
    networks:
      - public
      - internal

  server:
    build: server
    container_name: fligno_server
    ports:
      - 9090:80
    depends_on:
      - mysql
    volumes:
      - "./server:/var/www/html"
    networks:
      - internal

networks:
  public:
    external: false
  internal:
    external: false